[package]
name = "msgpack-rpc"
version = "0.1.0"
authors = ["Andy Russell <arussell123@gmail.com>"]

[dependencies]
env_logger = "0.3"
rmp = "^0.7"
rmp-serde = "0.9.0"
serde = "*"

[dependencies.mioco]
git = "https://github.com/dpc/mioco"
